# Generated by Django 3.2.5 on 2021-12-31 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='create', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BM',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('changed_at', models.DateTimeField()),
                ('bm_type', models.CharField(choices=[('normal-poop', 'normal-poop'), ('pee', 'pee'), ('poop&pee', 'poop&pee'), ('diarrhea', 'diarrhea'), ('constipated', 'constipated')], max_length=300)),
                ('amount', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=300)),
                ('color', models.CharField(choices=[('yellow', 'yellow'), ('brown', 'brown'), ('green', 'green')], max_length=300)),
            ],
            bases=('main.basemodel',),
        ),
        migrations.CreateModel(
            name='CarMaintenance',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('car', models.CharField(choices=[('blue-camry', 'blue-camry'), ('white-camry', 'white-camry')], max_length=300)),
                ('completed_at', models.DateTimeField()),
                ('maintenance_type', models.CharField(choices=[('gas', 'gas'), ('oil', 'oil'), ('tire', 'tire'), ('maintenance', 'maintenance'), ('repair', 'repair')], max_length=300)),
                ('maintenance_details', models.CharField(max_length=300)),
                ('notes', models.CharField(max_length=300)),
            ],
            bases=('main.basemodel',),
        ),
        migrations.CreateModel(
            name='MilkFeeding',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('ate_at', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=1, max_digits=5)),
                ('formula_type', models.CharField(default='Pro Advance - Similac', max_length=300)),
                ('formula_percent', models.IntegerField(help_text='Enter percentage out of 100.')),
                ('breast_milk_percent', models.IntegerField(default=0, help_text='Enter percentage out of 100.')),
            ],
            bases=('main.basemodel',),
        ),
    ]
